[toolchain]
anchor_version = "0.31.0"

[features]
seeds = true

[programs.testnet]
gumball_nft = "2V4iVvbNFXAa44frz12YUZJgJiQhcYTxbok9CNUUruC4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.testnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
