[toolchain]
anchor_version = "0.31.0"

[features]
seeds = true

[programs.testnet]
gumball_nft = "fyPh36k684kpZBhu32UcYLW1cxov2XdKZ2R6pXWRm9F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.testnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
